### ISSUE TITLE
Similar issue.

### ISSUE THREAD

**Issue by leftdevel** [doodeck/lambda-modules#1]
Hi there. Sorry for bothering you, but I'm in a pretty similar situation and just wanted to know if you managed to figure out how to correctly create the zip archive?

I tried zipping from Mac and Linux (ubuntu), both zip archives triggers an error when uploading to aws lambda, via the UI. There is an error box but no error message at all, so I'm completely lost and have no clue what's going on. 

Thanks in advance.

**Comment by leftdevel** [comment]
Just found the bug, and it is on the AWS SDK v2 for PHP. It was never the way I created the zip file :S

**Comment by doodeck** [comment]
Congratulations! Back then I didn't investigate deep enough and simply changed the workflow to the one which bypass the faulty compression method.
